"""ORM models package.

Importing this package registers every model on ``Base.metadata``.
"""

from backend.app.db.models.ai import AiMetric, AiRecord
from backend.app.db.models.audience import (
    AudienceSource,
    AudienceUser,
    Completeness,
    MemberStatus,
    ScanStatus,
    SourceType,
    SourceUserLink,
)
from backend.app.db.models.backup_destination import (
    DESTINATION_TITLES,
    BackupDestination,
    DestinationKind,
    DestinationStatus,
)
from backend.app.db.models.binding import (
    FUNCTION_EDITING,
    FUNCTION_POSTING,
    FUNCTION_REACTIONS,
    FUNCTION_TITLES,
    BindingRole,
    BindingStatus,
    BotChannelBinding,
)
from backend.app.db.models.bot import Bot, BotHealth, BotKind
from backend.app.db.models.bot_factory import (
    BATCH_STATUS_TITLES,
    BOT_CREATE_LIMIT_NOTE,
    CANDIDATE_STATUS_TITLES,
    TERMINAL_CANDIDATE_STATUSES,
    BatchStatus,
    BotBatch,
    BotCandidate,
    CandidateStatus,
)
from backend.app.db.models.campaign import (
    CampaignStatus,
    InviteCampaign,
    InviteLink,
    JoinRequest,
    JoinRequestStatus,
    LinkStatus,
)
from backend.app.db.models.capability import (
    CAPABILITY_ERROR,
    CAPABILITY_MESSAGES,
    CAPABILITY_OK,
    CAPABILITY_UNAVAILABLE,
    CAPABILITY_UNKNOWN,
    ChannelCapabilities,
)
from backend.app.db.models.channel import Channel, ChannelKind, ChannelStatus
from backend.app.db.models.content import (
    ButtonSet,
    CommentPlan,
    ContentItem,
    ContentItemStatus,
    ContentSource,
    ContentSourceKind,
    ContentSourceStatus,
    MediaAsset,
    Publication,
    PublicationStatus,
    RightsStatus,
)
from backend.app.db.models.donor import (
    CONFIDENCE_HIGH,
    CONFIDENCE_LOW,
    CONFIDENCE_MEDIUM,
    PROBABILITY_HIGH,
    PROBABILITY_LOW,
    PROBABILITY_MEDIUM,
    PROBABILITY_TITLES,
    QUALITY_AVERAGE,
    QUALITY_GOOD,
    QUALITY_SUSPECT,
    QUALITY_TITLES,
    QUALITY_UNKNOWN,
    DonorMetrics,
)
from backend.app.db.models.donor_candidate import (
    FIT_CHECK,
    FIT_DOUBTFUL,
    FIT_SUITABLE,
    FIT_TITLES,
    FIT_UNKNOWN,
    SOURCE_MANUAL,
    SOURCE_TELEGRAM,
    SOURCE_TITLES,
    SOURCE_WEB,
    DonorCandidate,
)
from backend.app.db.models.event import Event, EventLevel
from backend.app.db.models.invite import (
    TERMINAL_INVITE_STATUSES,
    InviteJob,
    InviteJobStatus,
    InviteStatus,
    InviteTask,
)
from backend.app.db.models.job import Job, JobStatus
from backend.app.db.models.mesh import (
    ALL_CAPABILITIES,
    CAPABILITY_TITLES,
    MODE_TITLES,
    PEER_STATUS_TITLES,
    LeaseStatus,
    MeshLease,
    MeshMode,
    MeshNode,
    MeshPeer,
    MeshRole,
    PairingCode,
    PeerStatus,
)
from backend.app.db.models.onboarding import (
    PRESET_ADVANCED,
    PRESET_BASIC,
    PRESET_BOT_ONLY,
    PRESET_MINIMAL,
    PRESET_PROFESSIONAL,
    PromotionProgress,
)
from backend.app.db.models.permission import PermissionCheck
from backend.app.db.models.post import Post, PostStatus
from backend.app.db.models.proxy import (
    KIND_TITLES,
    STATUS_TITLES,
    ProxyKind,
    ProxyProfile,
    ProxyStatus,
)
from backend.app.db.models.reaction import (
    DelayPresetDB,
    ReactionJob,
    ReactionJobStatus,
    ReactionProfile,
    ReactionRule,
)
from backend.app.db.models.session import SessionStatus, UserSession
from backend.app.db.models.setting import Setting
from backend.app.db.models.update_state import (
    UPDATE_APPLYING,
    UPDATE_AVAILABLE,
    UPDATE_CHECKING,
    UPDATE_DOWNLOADED,
    UPDATE_ERROR,
    UPDATE_FAILED,
    UPDATE_IDLE,
    UPDATE_MESSAGES,
    UPDATE_UP_TO_DATE,
    UpdateState,
)

__all__ = [
    "ALL_CAPABILITIES",
    "BATCH_STATUS_TITLES",
    "BOT_CREATE_LIMIT_NOTE",
    "CANDIDATE_STATUS_TITLES",
    "CAPABILITY_ERROR",
    "CAPABILITY_MESSAGES",
    "CAPABILITY_OK",
    "CAPABILITY_TITLES",
    "CAPABILITY_UNAVAILABLE",
    "CAPABILITY_UNKNOWN",
    "CONFIDENCE_HIGH",
    "CONFIDENCE_LOW",
    "CONFIDENCE_MEDIUM",
    "DESTINATION_TITLES",
    "FIT_CHECK",
    "FIT_DOUBTFUL",
    "FIT_SUITABLE",
    "FIT_TITLES",
    "FIT_UNKNOWN",
    "FUNCTION_EDITING",
    "FUNCTION_POSTING",
    "FUNCTION_REACTIONS",
    "FUNCTION_TITLES",
    "KIND_TITLES",
    "MODE_AUTO",
    "MODE_MANUAL",
    "MODE_SEMI_AUTO",
    "MODE_TITLES",
    "PEER_STATUS_TITLES",
    "PRESET_ADVANCED",
    "PRESET_BASIC",
    "PRESET_BOT_ONLY",
    "PRESET_MINIMAL",
    "PRESET_PROFESSIONAL",
    "PROBABILITY_HIGH",
    "PROBABILITY_LOW",
    "PROBABILITY_MEDIUM",
    "PROBABILITY_TITLES",
    "QUALITY_AVERAGE",
    "QUALITY_GOOD",
    "QUALITY_SUSPECT",
    "QUALITY_TITLES",
    "QUALITY_UNKNOWN",
    "SOURCE_MANUAL",
    "SOURCE_TELEGRAM",
    "SOURCE_TITLES",
    "SOURCE_WEB",
    "STATUS_TITLES",
    "TERMINAL_CANDIDATE_STATUSES",
    "TERMINAL_INVITE_STATUSES",
    "UPDATE_APPLYING",
    "UPDATE_AVAILABLE",
    "UPDATE_CHECKING",
    "UPDATE_DOWNLOADED",
    "UPDATE_ERROR",
    "UPDATE_FAILED",
    "UPDATE_IDLE",
    "UPDATE_MESSAGES",
    "UPDATE_UP_TO_DATE",
    "VALID_MODES",
    "AiMetric",
    "AiRecord",
    "AudienceSource",
    "AudienceUser",
    "BackupDestination",
    "BatchStatus",
    "BindingRole",
    "BindingStatus",
    "Bot",
    "BotBatch",
    "BotCandidate",
    "BotChannelBinding",
    "BotHealth",
    "BotKind",
    "ButtonSet",
    "CampaignStatus",
    "CandidateStatus",
    "Channel",
    "ChannelCapabilities",
    "ChannelKind",
    "ChannelStatus",
    "CommentPlan",
    "Completeness",
    "ContentItem",
    "ContentItemStatus",
    "ContentSource",
    "ContentSourceKind",
    "ContentSourceStatus",
    "DelayPresetDB",
    "DestinationKind",
    "DestinationStatus",
    "DonorCandidate",
    "DonorMetrics",
    "Event",
    "EventLevel",
    "InviteCampaign",
    "InviteJob",
    "InviteJobStatus",
    "InviteLink",
    "InviteStatus",
    "InviteTask",
    "Job",
    "JobStatus",
    "JoinRequest",
    "JoinRequestStatus",
    "LeaseStatus",
    "LinkStatus",
    "MediaAsset",
    "MemberStatus",
    "MeshLease",
    "MeshMode",
    "MeshNode",
    "MeshPeer",
    "MeshRole",
    "PairingCode",
    "PeerStatus",
    "PermissionCheck",
    "Post",
    "PostStatus",
    "PromotionProgress",
    "ProxyKind",
    "ProxyProfile",
    "ProxyStatus",
    "Publication",
    "PublicationStatus",
    "ReactionJob",
    "ReactionJobStatus",
    "ReactionProfile",
    "ReactionRule",
    "RightsStatus",
    "ScanStatus",
    "SessionStatus",
    "Setting",
    "SourceType",
    "SourceUserLink",
    "UpdateState",
    "UserSession",
]
