"""Meta-audit core: silent-failure guard, runtime drift, generated kill rate.

Companion to ``tests/test_consistency_mutations.py``. It proves the guarantees
the Consistency Auditor must keep (D-099, D-102):

1. **A failing check never becomes a pass.** If a registered check raises, the
   runner emits ``audit.check_failed.<name>`` with severity ``error``.
2. **The runtime (DB-backed) checks detect real drift** — a dead setting and a
   channel-aware row without a channel reference.
3. **The kill rate is computed, not declared.** ``agent/META_AUDIT_RESULT.json``
   is generated by executing every mutation and classifying the result; it
   carries ``result_source: computed from runtime mutation executions`` and the
   arithmetic is asserted here and in CI.

No Telegram credentials, sessions, TDATA, network or production data are used.
"""

from __future__ import annotations

import asyncio
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest
from httpx import AsyncClient

from backend.app import __version__
from backend.app.services.consistency import ConsistencyAuditor
from backend.app.services.consistency_types import (
    HEALTH_FAIL,
    SEVERITY_ERROR,
    build_report,
)
from tests.meta_audit.engine import (
    RESULT_SOURCE,
    report_path,
    run_suite,
    write_report,
)
from tests.meta_audit.mutations import KNOWN_GAP_IDS, MUTATIONS, NEGATIVE_CONTROLS

REPO_ROOT = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# 1. Silent-failure guard
# ---------------------------------------------------------------------------
def _run_with_broken_check(monkeypatch: pytest.MonkeyPatch, name: str) -> list:
    """Replace one static check with one that raises, then run the suite."""
    import backend.app.services.consistency_checks as cc

    def boom() -> list:
        raise RuntimeError("SYNTHETIC AUDIT FAILURE")

    boom.__name__ = name
    monkeypatch.setattr(cc, name, boom)
    return cc.run_static_checks()


def test_a_raising_static_check_is_reported_not_swallowed(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    findings = _run_with_broken_check(monkeypatch, "check_i18n_completeness")
    failed = [f for f in findings if f.id == "audit.check_failed.check_i18n_completeness"]
    assert failed, "a raising check disappeared instead of being reported"
    assert failed[0].severity == SEVERITY_ERROR


def test_a_raising_static_check_makes_the_report_fail(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    report = build_report(_run_with_broken_check(monkeypatch, "check_model_migration"))
    assert report.overall == HEALTH_FAIL
    assert report.counts[SEVERITY_ERROR] >= 1


def test_broken_source_check_reports_info_not_error(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # A source-comparison check must degrade to "unavailable" (info), never raise
    # into a false error, and never silently vanish (D-096).
    import backend.app.services.consistency_checks as cc

    monkeypatch.setattr(cc, "FRONTEND", tmp_path / "frontend-absent")
    findings = cc.run_static_checks()
    ids = {f.id for f in findings}
    assert "audit.source_unavailable.check_api_route_frontend_client" in ids
    assert "audit.source_unavailable.check_hardcoded_ui_strings" in ids
    assert not any(i.startswith("audit.check_failed.") for i in ids)
    unavailable = [f for f in findings if f.id.startswith("audit.source_unavailable.")]
    assert all(f.severity == "info" for f in unavailable)


async def test_a_raising_runtime_check_is_reported_not_swallowed(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    async def boom(self) -> list:
        raise RuntimeError("SYNTHETIC RUNTIME FAILURE")

    monkeypatch.setattr(ConsistencyAuditor, "_check_dead_settings", boom)
    from backend.app.db.session import get_session_factory

    async with get_session_factory()() as session:
        report = await ConsistencyAuditor(session).run()
    assert "audit.check_failed.boom" in {f.id for f in report.findings}
    assert report.overall == HEALTH_FAIL


# ---------------------------------------------------------------------------
# 2. Runtime (DB-backed) drift detection
# ---------------------------------------------------------------------------
async def test_runtime_detects_dead_setting(client: AsyncClient) -> None:
    # A persisted setting no module reads must surface as an orphan finding.
    from backend.app.db.repositories.settings import SettingRepository
    from backend.app.db.session import get_session_factory

    async with get_session_factory()() as session:
        await SettingRepository(session).upsert("zz_ghost_setting", "1", value_type="int")
        report = await ConsistencyAuditor(session).run()
    assert "settings.dead.zz_ghost_setting" in {f.id for f in report.findings}


async def test_runtime_detects_channel_aware_row_without_channel(
    client: AsyncClient,
) -> None:
    # A channel-aware table row with no channel_id must be flagged.
    from backend.app.db.models.content import ContentSource
    from backend.app.db.session import get_session_factory

    async with get_session_factory()() as session:
        session.add(ContentSource(title="ghost", reference="", channel_id=""))
        await session.commit()
        report = await ConsistencyAuditor(session).run()
    assert "channel-aware.content_source" in {f.id for f in report.findings}


# ---------------------------------------------------------------------------
# 3. The kill rate is generated by execution, not declared
# ---------------------------------------------------------------------------
def test_report_is_generated_from_runtime_execution(tmp_path: Path) -> None:
    out = tmp_path / "META_AUDIT_RESULT.json"

    async def _run():
        import tempfile

        with tempfile.TemporaryDirectory() as td:
            return await run_suite(Path(td), MUTATIONS, NEGATIVE_CONTROLS)

    suite = asyncio.run(_run())
    payload = write_report(suite, out)

    assert payload["result_source"] == RESULT_SOURCE
    # Every mutation carries a runtime-computed ``detected`` boolean.
    assert len(payload["mutations"]) == len(MUTATIONS)
    assert all(isinstance(m["detected"], bool) for m in payload["mutations"])
    # Arithmetic holds, computed from the executions.
    assert payload["detected"] + payload["missed"] == payload["total"]
    assert payload["kill_rate"] == round(payload["detected"] / payload["total"] * 100, 1)
    # Negative controls ran and produced no false positive.
    assert payload["false_positives"] == 0
    assert len(payload["negative_controls"]) == len(NEGATIVE_CONTROLS)
    # The committed report must match the same schema and provenance.
    committed = json.loads(report_path().read_text(encoding="utf-8"))
    assert committed["result_source"] == RESULT_SOURCE
    assert committed["detected"] + committed["missed"] == committed["total"]


def test_report_arithmetic_is_self_consistent(tmp_path: Path) -> None:
    async def _run():
        import tempfile

        with tempfile.TemporaryDirectory() as td:
            return await run_suite(Path(td), MUTATIONS, NEGATIVE_CONTROLS)

    suite = asyncio.run(_run())
    suite.verify()
    assert suite.detected + suite.missed == suite.total
    assert suite.kill_rate == round(suite.detected / suite.total * 100, 1)
    assert suite.critical_misses == sum(
        1 for m in suite.mutations if not m.detected and m.severity == "critical"
    )


# ---------------------------------------------------------------------------
# 4. Cross-file release hygiene
# ---------------------------------------------------------------------------
def test_repo_version_is_consistent() -> None:
    import tomllib

    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    package = json.loads((REPO_ROOT / "frontend" / "package.json").read_text(encoding="utf-8"))
    lock = json.loads(
        (REPO_ROOT / "frontend" / "package-lock.json").read_text(encoding="utf-8")
    )
    assert __version__ == pyproject["project"]["version"] == package["version"]
    # The lockfile carries the same version twice; a stale lock (1.7.0 while the
    # app reads 1.8.0) is drift the docs used to claim did not exist.
    assert lock["version"] == __version__
    assert lock["packages"][""]["version"] == __version__


def test_readme_states_the_current_release() -> None:
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    assert f"`v{__version__}`" in readme


def test_memory_files_state_the_current_release() -> None:
    """CURRENT_STATE.md and NEXT_TASK.md must not advertise a stale version.

    Both carry a one-line "Version string(s) ..." anchor for the *current* release
    (the first such line); earlier historical lines legitimately name older
    versions, so only the first occurrence is checked. It must name the shipped
    version so a new agent resuming from these files is not misled.
    """
    for name in ("agent/CURRENT_STATE.md", "agent/NEXT_TASK.md"):
        text = (REPO_ROOT / name).read_text(encoding="utf-8")
        anchors = [ln for ln in text.splitlines() if "Version string" in ln]
        assert anchors, f"{name} lost its version anchor line"
        assert f"**{__version__}**" in anchors[0], (
            f"{name} advertises a stale current version: {anchors[0]!r}"
        )


def test_release_checklist_covers_the_current_release() -> None:
    checklist = (REPO_ROOT / "docs" / "RELEASE_CHECKLIST.md").read_text(encoding="utf-8")
    assert f"### v{__version__} " in checklist, (
        f"docs/RELEASE_CHECKLIST.md has no verification section for v{__version__}"
    )


def test_result_report_matches_version() -> None:
    committed = json.loads(report_path().read_text(encoding="utf-8"))
    assert committed["version"] == __version__


def test_architecture_doc_meta_audit_counts_match_report() -> None:
    """docs/ARCHITECTURE.md's current meta-audit counts must match reality.

    The architecture doc narrates the *current* mutation engine ("There are N
    mutations and M negative controls" / "Current run: N total, N detected, …").
    A release that adds mutations bumps the report but used to leave this prose
    stale (it still read 25/25/5 while the report and code were at 32/32/8).
    This guard pins the prose to the committed report and the mutation registry.
    """
    from tests.meta_audit import mutations

    report = json.loads(report_path().read_text(encoding="utf-8"))
    architecture = (REPO_ROOT / "docs" / "ARCHITECTURE.md").read_text(encoding="utf-8")

    total = report["total"]
    mutations_declared = len(mutations.MUTATIONS)
    controls_declared = len(mutations.NEGATIVE_CONTROLS)

    assert total == mutations_declared == len(report["mutations"]), (
        "the generated report and the mutation registry disagree on the count"
    )
    assert f"There are {mutations_declared} mutations" in architecture, (
        f"docs/ARCHITECTURE.md does not state the real mutation count "
        f"({mutations_declared})"
    )
    assert f"and {controls_declared} negative controls" in architecture, (
        f"docs/ARCHITECTURE.md does not state the real negative-control count "
        f"({controls_declared})"
    )
    assert f"Current run: **{total} total, {total} detected" in architecture, (
        f"docs/ARCHITECTURE.md current-run line is stale (expected {total}/{total})"
    )


#: Lines that *assert the current release* (as opposed to narrating history).
#: Each entry is ``(file, required_prefix, window)``: the first line in the file
#: whose stripped text starts with the prefix must name the shipped version
#: within the first ``window`` characters. These are exactly the lines a resuming
#: agent reads first, so a stale version here is the dangerous drift.
_CURRENT_ANCHORS = (
    ("agent/CURRENT_STATE.md", "**Current phase:**", 220),
    ("agent/CURRENT_STATE.md", "**Factual git state:**", 130),
    ("agent/NEXT_TASK.md", "**Status:**", 220),
)

#: Mid-line phrases that assert the current release. A line carrying one of these
#: must not name a *different* version, unless the line is explicitly narrating
#: history (it also contains one of ``_HISTORY_MARKERS``). This catches stale
#: "… Latest release: vX.Y.Z" / "**Repository status:** … vX.Y.Z" lines while
#: leaving "README.md still said …" drift notes alone.
_MIDLINE_CLAIMS = ("Latest release:", "**Repository status:")
_HISTORY_MARKERS = (
    "history",
    "historical",
    "said",
    "still",
    "superseded",
    "legacy",
    "Earlier",
    "Previous",
    "previous",
)


def test_memory_files_have_no_stale_current_version() -> None:
    """Guard CURRENT_STATE/NEXT_TASK against stale *current release* facts.

    A new agent resumes from these files, so the lines that claim to describe
    the *current* state must name the shipped version — not an older one and not
    an invented future one. Historical release lines (``**v1.8.1 RELEASED`` …)
    and explicit drift notes ("README.md still said …") are exempt: they narrate
    the past on purpose. This reproduces the regression these files hit before —
    advertising ``v1.8.0`` as the latest release while ``v1.8.2`` was shipped.
    """
    import re

    current = f"v{__version__}"
    parsed = tuple(int(p) for p in __version__.split("."))
    failures: list[str] = []

    def _versions(line: str) -> list[tuple[int, int, int]]:
        return [
            tuple(int(g) for g in m.groups())
            for m in re.finditer(r"v(\d+)\.(\d+)\.(\d+)", line)
        ]

    for name in ("agent/CURRENT_STATE.md", "agent/NEXT_TASK.md"):
        lines = (REPO_ROOT / name).read_text(encoding="utf-8").splitlines()
        for prefix, window in ((p, w) for f, p, w in _CURRENT_ANCHORS if f == name):
            match = next((ln for ln in lines if ln.strip().startswith(prefix)), None)
            if match is None:
                failures.append(f"{name}: missing current-release anchor {prefix!r}")
                continue
            if current not in match[:window]:
                failures.append(
                    f"{name}: {prefix!r} line does not name {current} within {window} chars"
                )
            if any(v > parsed for v in _versions(match[:window])):
                failures.append(f"{name}: {prefix!r} line claims an unreleased version")
        for lineno, line in enumerate(lines, start=1):
            if not any(claim in line for claim in _MIDLINE_CLAIMS):
                continue
            if any(marker in line for marker in _HISTORY_MARKERS):
                continue
            named = _versions(line)
            if named and not any(v == parsed for v in named):
                failures.append(
                    f"{name}:{lineno} asserts a stale current release: {line[:140]!r}"
                )

    assert not failures, "stale current-release facts in memory files:\n" + "\n".join(failures)


def test_changelog_leads_with_the_current_release() -> None:
    """CHANGELOG's newest section must be the shipped version (not a stale one)."""
    import re

    changelog = (REPO_ROOT / "agent" / "CHANGELOG.md").read_text(encoding="utf-8")
    heading = re.search(r"^## \[([0-9.]+)\]", changelog, flags=re.MULTILINE)
    assert heading is not None, "agent/CHANGELOG.md has no versioned section"
    assert heading.group(1) == __version__, (
        f"agent/CHANGELOG.md leads with {heading.group(1)}; expected {__version__}"
    )


# ---------------------------------------------------------------------------
# 5. Capability dependency actually blocks availability (not just a static warn)
# ---------------------------------------------------------------------------
def test_dependency_on_unimplemented_capability_blocks_availability(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import dataclasses

    from backend.app.services import capability_graph as cg

    donor = next(c for c in cg.CAPABILITIES if c.key == "donor_discovery")
    # ``media_conversion`` is registered but not implemented: a dependency on it
    # must block availability (``config_sync`` is implemented as of v1.6).
    patched = dataclasses.replace(donor, requires=("media_conversion",))
    monkeypatch.setattr(
        cg,
        "CAPABILITIES",
        tuple(patched if c.key == "donor_discovery" else c for c in cg.CAPABILITIES),
    )
    context = {req: True for cap in cg.CAPABILITIES for req in cap.requires}
    context["media_conversion"] = True
    state = cg.evaluate(patched, context)
    assert state.state != cg.STATE_AVAILABLE
    assert any("media_conversion" in m for m in state.missing)


# ---------------------------------------------------------------------------
# 6. Closed gaps M (write-only setting), N (unused DB field), O (service without
#    caller), P (frontend control without behaviour) and Q (channel-aware drift)
# ---------------------------------------------------------------------------
def _mutation(mutation_id: str):
    return next(m for m in MUTATIONS if m.id == mutation_id)


def test_write_only_setting_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """M: a setting written but never read must be flagged by the real auditor."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("M_write_only_setting"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "a write-only setting is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_channel_aware_module_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """Q: channel-aware code that bypasses the registry must be flagged."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("Q_channel_aware_module"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "a channel-aware module without a canonical link is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_unused_db_field_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """N: a column no module reads or writes must be flagged."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("N_unused_db_field"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "an unused DB column is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_service_without_caller_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """O: a public service class no module references must be flagged."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("O_service_without_caller"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "a backend service without a caller is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_control_without_behavior_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """P: a template handler with no defined function must be flagged."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("P_control_without_behavior"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "a frontend control without behaviour is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_gateway_capability_dependency_mutation_is_detected(tmp_path: Path) -> None:
    """A gateway depending on an unimplemented capability must fail the graph."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(
        run_mutation(_mutation("X_gateway_capability_dependency"), tmp_path)
    )
    assert result.error is None
    assert result.detected is True, (
        "an AI Gateway dependency on an unimplemented capability is no longer "
        f"detected: {[f['id'] for f in result.actual_findings]}"
    )


def test_gateway_provider_orphan_mutation_is_detected(tmp_path: Path) -> None:
    """A gateway provider class nothing references must be flagged as dead."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("Y_gateway_provider_orphan"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "a gateway provider without a caller is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_gateway_unwired_control_mutation_is_detected(tmp_path: Path) -> None:
    """An AI Gateway UI control with no handler must be flagged."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("Z_gateway_unwired_control"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "an unwired AI Gateway control is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_all_original_gaps_are_closed() -> None:
    assert len(KNOWN_GAP_IDS) == 0
    for gap in (
        "M_write_only_setting",
        "N_unused_db_field",
        "O_service_without_caller",
        "P_control_without_behavior",
        "Q_channel_aware_module",
    ):
        assert gap not in KNOWN_GAP_IDS


@pytest.mark.parametrize(
    ("mutation_id", "detector"),
    [
        ("M_write_only_setting", "check_write_only_settings"),
        ("N_unused_db_field", "check_unused_model_columns"),
        ("O_service_without_caller", "check_orphan_service_classes"),
        ("P_control_without_behavior", "check_frontend_unwired_controls"),
        ("Q_channel_aware_module", "check_channel_registry_usage"),
    ],
)
def test_removing_a_gap_detector_turns_it_into_a_miss(
    mutation_id: str, detector: str, tmp_path: Path
) -> None:
    """Dynamism: removing each gap detector must flip its mutation back to MISS."""
    from tests.meta_audit.engine import run_mutation

    before = asyncio.run(run_mutation(_mutation(mutation_id), tmp_path / "before"))
    assert before.detected is True
    after = asyncio.run(
        run_mutation(
            _mutation(mutation_id), tmp_path / "after", disabled_checks=(detector,)
        )
    )
    assert after.detected is False


def test_committed_report_records_all_gaps_as_detected() -> None:
    committed = json.loads(report_path().read_text(encoding="utf-8"))
    by_id = {m["id"]: m for m in committed["mutations"]}
    for gap in (
        "M_write_only_setting",
        "N_unused_db_field",
        "O_service_without_caller",
        "P_control_without_behavior",
        "Q_channel_aware_module",
    ):
        assert by_id[gap]["detected"] is True, gap
    assert committed["high_misses"] == 0
    assert committed["missed"] == 0
    assert committed["kill_rate"] == 100.0


# ---------------------------------------------------------------------------
# 6. Post-release hygiene: no stale release facts left behind
# ---------------------------------------------------------------------------
#: ``(file, regex)`` pairs for release-version headings. The value captured by
#: group 1 must be the version the repository currently ships. These are the
#: exact spots a release has historically left stale (the CHANGELOG header, the
#: release-verification sections and the roadmap history), so the guard pins
#: them to the shipped version instead of trusting a manual edit.
_VERSION_HEADINGS = (
    ("agent/CHANGELOG.md", r"^## \[([0-9]+\.[0-9]+\.[0-9]+)\]"),
    ("docs/RELEASE_CHECKLIST.md", r"^### v([0-9]+\.[0-9]+\.[0-9]+) "),
    ("docs/ROADMAP.md", r"^- \*\*v([0-9]+\.[0-9]+\.[0-9]+) \("),
)

#: Version strings written into the release-verification sections. A release
#: bumps the app version, so a stale ``**NNN passed**`` here is drift.
_TEST_COUNT_RE = re.compile(r"(\d+) passed(?:, (\d+) skipped)?")
_CHANGELOG_PASSED_RE = re.compile(r"full suite green \(\*\*(\d+) passed")


def test_versioned_docs_lead_with_the_shipped_release() -> None:
    """Every versioned doc heading must lead with the shipped version.

    Reproduces the drift this repository kept hitting: the CHANGELOG, the release
    checklist and the roadmap named an older (or, worse, an invented future)
    release as the newest one. Only the *first* heading in each file is checked;
    the rest are history.
    """
    for name, pattern in _VERSION_HEADINGS:
        text = (REPO_ROOT / name).read_text(encoding="utf-8")
        match = re.search(pattern, text, flags=re.MULTILINE)
        assert match is not None, f"{name} lost its versioned heading"
        assert match.group(1) == __version__, (
            f"{name} leads with v{match.group(1)}; expected v{__version__}"
        )


def test_release_docs_do_not_claim_an_unreleased_version() -> None:
    """No release doc may name a version newer than the shipped one.

    A future version cannot exist yet, so any such claim is a fabricated date or
    version — the same class of error as the wrong v1.9.0 release date.
    """
    current = tuple(int(p) for p in __version__.split("."))
    offenders: list[str] = []
    for name in (
        "README.md",
        "agent/CHANGELOG.md",
        "agent/CURRENT_STATE.md",
        "agent/NEXT_TASK.md",
        "agent/DECISIONS.md",
        "docs/RELEASE_CHECKLIST.md",
        "docs/ROADMAP.md",
    ):
        text = (REPO_ROOT / name).read_text(encoding="utf-8")
        for match in re.finditer(r"v(\d+)\.(\d+)\.(\d+)", text):
            version = tuple(int(g) for g in match.groups())
            if version > current:
                offenders.append(f"{name}: v{match.group(0)[1:]}")
    assert not offenders, "release docs name an unreleased version:\n" + "\n".join(
        sorted(set(offenders))
    )


def test_release_docs_do_not_claim_a_future_date() -> None:
    """No release doc may name a calendar date in the future.

    Release dates must come from git/GitHub, not be invented. v1.9.0 was once
    documented as released on 2026-10-12 while the tag and GitHub Release are
    dated 2026-10-08; this guard makes a future date impossible to commit.
    """
    import datetime

    today = datetime.datetime.now(datetime.UTC).date()
    offenders: list[str] = []
    for name in (
        "README.md",
        "agent/CHANGELOG.md",
        "agent/CURRENT_STATE.md",
        "agent/NEXT_TASK.md",
        "agent/DECISIONS.md",
        "docs/RELEASE_CHECKLIST.md",
        "docs/ROADMAP.md",
    ):
        text = (REPO_ROOT / name).read_text(encoding="utf-8")
        for match in re.finditer(r"\b(20\d\d)-(\d\d)-(\d\d)\b", text):
            try:
                date = datetime.date(*(int(g) for g in match.groups()))
            except ValueError:
                continue
            if date > today:
                offenders.append(f"{name}: {date.isoformat()}")
    assert not offenders, "release docs name a future date:\n" + "\n".join(
        sorted(set(offenders))
    )


def _git_output(*args: str) -> str | None:
    """Return stdout of a git command, or None if git cannot answer.

    Absent (shallow / tagless) history is treated as "cannot verify", never as a
    failure, so the guard never turns missing git data into a false alarm.
    """
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.stdout.strip()


def _passed_counts(text: str) -> list[int]:
    return [int(m.group(1)) for m in _TEST_COUNT_RE.finditer(text)]


_FULL_SUITE_SIZE: int | None = None


def _full_suite_size() -> int:
    """Return the number of tests in the whole suite (collected in a subprocess).

    Collecting the entire suite (rather than the currently-running selection)
    means the documented full-suite count is checked against the real full-suite
    size even when a subset (e.g. the CI ``meta-audit`` job) is running.
    """
    global _FULL_SUITE_SIZE
    if _FULL_SUITE_SIZE is None:
        # ``-o addopts=`` drops the repo's ``-q`` so pytest prints its
        # "N tests collected" summary instead of the per-file listing.
        result = subprocess.run(
            [sys.executable, "-m", "pytest", "--collect-only", "-o", "addopts=", "-q"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
        )
        match = re.search(r"(\d+) tests? collected", result.stdout)
        assert match is not None, (
            "could not determine the full-suite test count:\n" + result.stdout[-2000:]
        )
        _FULL_SUITE_SIZE = int(match.group(1))
    return _FULL_SUITE_SIZE


def test_memory_files_do_not_claim_a_stale_test_count() -> None:
    """The documented full-suite count must not exceed the suite's own size.

    No doc may claim more tests passed than the suite actually contains. This is
    the sound half of the count guard (a count can only be *proven* wrong when it
    exceeds reality); the staleness half is
    :func:`test_documented_test_count_grows_across_releases`.
    """
    collected_count = _full_suite_size()
    offenders: list[str] = []
    for name in ("README.md", "agent/CHANGELOG.md", "agent/CURRENT_STATE.md"):
        text = (REPO_ROOT / name).read_text(encoding="utf-8")
        for match in _TEST_COUNT_RE.finditer(text):
            passed = int(match.group(1))
            skipped = int(match.group(2) or 0)
            if passed + skipped > collected_count:
                offenders.append(
                    f"{name}: claims {passed} passed (+{skipped} skipped) "
                    f"> {collected_count} tests"
                )
    assert not offenders, "documented test count exceeds the real suite:\n" + "\n".join(
        sorted(set(offenders))
    )


def test_documented_test_count_grows_across_releases() -> None:
    """Each release's documented pass count must exceed the previous release's.

    The suite only ever grows, so a release that leaves the previous release's
    number in place (the classic copy-paste staleness) is caught here without a
    fragile tolerance: the current section's count must be strictly greater than
    the one below it. It also fails if the current section loses its count line.
    """
    text = (REPO_ROOT / "agent" / "CHANGELOG.md").read_text(encoding="utf-8")
    sections = list(re.finditer(r"^## \[([0-9.]+)\]", text, flags=re.MULTILINE))
    assert sections, "agent/CHANGELOG.md has no versioned sections"
    assert sections[0].group(1) == __version__, (
        f"CHANGELOG leads with {sections[0].group(1)}; expected {__version__}"
    )

    def _count(section: re.Match[str]) -> int | None:
        index = sections.index(section)
        end = sections[index + 1].start() if index + 1 < len(sections) else len(text)
        match = _CHANGELOG_PASSED_RE.search(text[section.end(): end])
        return int(match.group(1)) if match else None

    current_count = _count(sections[0])
    assert current_count is not None, (
        f"CHANGELOG section [{__version__}] lost its test-count line"
    )
    previous_count = next(
        (count for section in sections[1:] if (count := _count(section)) is not None),
        None,
    )
    if previous_count is not None:
        assert current_count > previous_count, (
            f"CHANGELOG documents {current_count} passed for v{__version__} but the "
            f"previous release already documented {previous_count} — a stale count "
            "left in place"
        )


def test_release_checklist_leads_with_the_shipped_release() -> None:
    """The newest verification section in the checklist must be the shipped one."""
    checklist = (REPO_ROOT / "docs" / "RELEASE_CHECKLIST.md").read_text(encoding="utf-8")
    match = re.search(r"^### v([0-9]+\.[0-9]+\.[0-9]+) ", checklist, flags=re.MULTILINE)
    assert match is not None, "docs/RELEASE_CHECKLIST.md has no versioned section"
    assert match.group(1) == __version__, (
        f"docs/RELEASE_CHECKLIST.md leads with v{match.group(1)}; expected v{__version__}"
    )


def test_next_task_has_no_completed_release_step() -> None:
    """NEXT_TASK.md must not still ask for an already-shipped release.

    Historically it kept a "Next step: release vX.Y.Z" (and "Release as vX.Y.Z")
    section for a version that had already shipped. This guard fails if the file
    asks to release the *current* version again, or instructs a release while
    also declaring that same version released.
    """
    text = (REPO_ROOT / "agent" / "NEXT_TASK.md").read_text(encoding="utf-8")
    current = __version__
    unreleased = re.compile(
        r"(?:Next step|Release as|Next task)[^\n]{0,80}?v" + re.escape(current)
    )
    match = unreleased.search(text)
    assert match is None, (
        f"agent/NEXT_TASK.md still asks to release the shipped v{current}: "
        f"{match.group(0)!r}"
    )
    if re.search(r"v" + re.escape(current) + r"[^\n]{0,40}\bRELEASED\b", text):
        assert not re.search(
            r"(?:Next step|Release as|Next task)[^\n]{0,80}?release", text
        ), "agent/NEXT_TASK.md declares the current release but still asks to release"


def test_next_task_release_anchors_match_git() -> None:
    """NEXT_TASK's stated ``main`` HEAD and tag must match the real repository.

    This catches a stale SHA left after the branch moved on. If git cannot answer
    (shallow clone), the check is skipped rather than failing.
    """
    text = (REPO_ROOT / "agent" / "NEXT_TASK.md").read_text(encoding="utf-8")
    head = _git_output("rev-parse", "--short", "main")
    tag = _git_output("describe", "--tags", "--exact-match", "main")
    if head is None or tag is None:  # pragma: no cover - shallow clone
        pytest.skip("git cannot resolve main/tag in this checkout")
    if tag != f"v{__version__}":  # pragma: no cover - pre-release branch state
        pytest.skip(f"main is not tagged v{__version__} (tag={tag!r})")
    assert f"`main` HEAD = `{head}`" in text, (
        f"agent/NEXT_TASK.md does not state the real main HEAD {head}"
    )
    assert tag in text, f"agent/NEXT_TASK.md does not name the current tag {tag}"


def test_current_state_release_anchors_match_git() -> None:
    """CURRENT_STATE's stated ``main`` HEAD and tag must match the real repo.

    The "Factual git state" line is one of the first things a resuming agent
    reads, so a stale SHA there misleads it about what has shipped. The parallel
    NEXT_TASK guard covers that file; this closes the same hole for CURRENT_STATE.
    If git cannot answer (shallow clone), the check is skipped rather than failing.
    """
    text = (REPO_ROOT / "agent" / "CURRENT_STATE.md").read_text(encoding="utf-8")
    head = _git_output("rev-parse", "--short", "main")
    tag = _git_output("describe", "--tags", "--exact-match", "main")
    if head is None or tag is None:  # pragma: no cover - shallow clone
        pytest.skip("git cannot resolve main/tag in this checkout")
    if tag != f"v{__version__}":  # pragma: no cover - pre-release branch state
        pytest.skip(f"main is not tagged v{__version__} (tag={tag!r})")
    assert f"`main` HEAD = `{head}`" in text, (
        f"agent/CURRENT_STATE.md does not state the real main HEAD {head}"
    )
    assert tag in text, (
        f"agent/CURRENT_STATE.md does not name the current tag {tag}"
    )


def test_next_task_names_the_latest_tag() -> None:
    """NEXT_TASK.md must name the repository's latest release tag.

    ``git tag --sort=-v:refname`` reports the newest tag by version; if NEXT_TASK
    names an older one (the classic stale "latest tag" left after a release), a
    new agent is misled about what has actually shipped. Version sorting is used
    rather than ``git describe`` because the latest tag points at the ``main``
    merge commit, which is not an ancestor of ``develop``. Skipped when git
    cannot answer (shallow/tagless checkout).
    """
    tags = _git_output("tag", "--sort=-v:refname")
    if not tags:  # pragma: no cover - shallow clone
        pytest.skip("git cannot list tags in this checkout")
    latest = tags.splitlines()[0]
    text = (REPO_ROOT / "agent" / "NEXT_TASK.md").read_text(encoding="utf-8")
    assert latest in text, (
        f"agent/NEXT_TASK.md does not name the latest release tag {latest}"
    )


def test_next_task_active_task_is_not_declared_released() -> None:
    """An 'Active task' section must not describe already-released work.

    This is the drift that had to be repaired by hand: NEXT_TASK kept an
    'Active task' heading over work that had already shipped. The body of the
    active section (up to the next heading) must not declare a RELEASED state —
    a shipped task belongs under a completed section, not the active one.
    """
    text = (REPO_ROOT / "agent" / "NEXT_TASK.md").read_text(encoding="utf-8")
    heading = re.search(
        r"^#+\s*Active task\b.*$", text, flags=re.MULTILINE | re.IGNORECASE
    )
    assert heading is not None, "agent/NEXT_TASK.md lost its 'Active task' heading"
    rest = text[heading.end():]
    next_heading = re.search(r"^#+\s", rest, flags=re.MULTILINE)
    body = rest[: next_heading.start()] if next_heading else rest
    assert not re.search(r"\bRELEASED\b", body), (
        "agent/NEXT_TASK.md 'Active task' section declares RELEASED work"
    )


#: Lines that claim what the *latest release* is, as ``(file, stripped_prefix)``.
#: These must name the shipped version; older versions may still appear later on
#: the same line (a "Previous release:" clause), so the mid-line stale-version
#: guard exempts such lines and cannot catch a stale anchor here.
_LATEST_RELEASE_ANCHORS = (
    ("README.md", "**Current stable release:"),
    ("agent/CURRENT_STATE.md", "**Factual git state:**"),
)


def test_latest_release_anchors_name_the_shipped_version() -> None:
    """The 'latest release' anchor lines must name the shipped version.

    Reproduces the drift where ``README.md`` advertised ``v1.4.0`` as the current
    stable release after later releases had shipped. ``test_readme_states_the_
    current_release`` only checks that the version appears *somewhere*, and the
    CURRENT_STATE factual-git-state line carries a "Previous release:" clause, so
    it is exempted by the historical-line guard — a stale "latest release" there
    would otherwise slip through. This guard checks the anchor lines directly.
    """
    current = f"v{__version__}"
    offenders: list[str] = []
    for name, prefix in _LATEST_RELEASE_ANCHORS:
        lines = (REPO_ROOT / name).read_text(encoding="utf-8").splitlines()
        match = next((ln for ln in lines if ln.strip().startswith(prefix)), None)
        assert match is not None, f"{name} lost its latest-release anchor {prefix!r}"
        if current not in match:
            offenders.append(f"{name}: {prefix!r} does not name {current}")
    assert not offenders, "stale latest-release anchor:\n" + "\n".join(offenders)
