"""Meta-audit: measure the Consistency Auditor by *execution* (D-102).

Every test here builds an isolated copy of the source tree, injects one seeded
defect, runs the **real** auditor, and asserts the finding it actually produced.
Detection is never read from a pre-declared list — the engine classifies each
mutation at runtime, so removing a detector flips the result automatically.

The working tree is never modified: each defect lives in a throwaway copy under
``tmp_path``. The kill-rate summary is generated by :mod:`tests.meta_audit.engine`
and written to ``agent/META_AUDIT_RESULT.json``.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest

from tests.meta_audit.engine import (
    Mutation,
    MutationResult,
    MutationSandbox,
    SuiteResult,
    run_mutation,
    run_suite,
)
from tests.meta_audit.mutations import (
    KNOWN_GAP_IDS,
    MUTATIONS,
    NEGATIVE_CONTROLS,
)

_MUTATION_IDS = [m.id for m in MUTATIONS]
_CONTROL_IDS = [c.id for c in NEGATIVE_CONTROLS]


def _run(mutation: Mutation, workdir: Path, *, disabled: tuple[str, ...] = ()) -> MutationResult:
    return asyncio.run(run_mutation(mutation, workdir, disabled_checks=disabled))


def _run_suite(
    workdir: Path,
    mutations: list[Mutation],
    controls: list[Mutation] | None = None,
) -> SuiteResult:
    return asyncio.run(run_suite(workdir, mutations, controls or []))


# ---------------------------------------------------------------------------
# 1. Every seeded defect is executed and classified at runtime
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("mutation", MUTATIONS, ids=_MUTATION_IDS)
def test_mutation_is_classified_by_real_execution(mutation: Mutation, tmp_path: Path) -> None:
    result = _run(mutation, tmp_path)
    # A mutation that errors during execution is a broken test, never a silent pass.
    assert result.error is None, f"{mutation.id} errored: {result.error}"

    if mutation.id in KNOWN_GAP_IDS:
        # A documented gap: the auditor is not expected to catch it *yet*. If it
        # starts catching it, remove the id from KNOWN_GAP_IDS so the kill rate
        # reflects reality.
        assert not result.detected, (
            f"{mutation.id} is now detected — remove it from KNOWN_GAP_IDS (D-100)"
        )
    else:
        assert result.detected, (
            f"{mutation.id}: expected {result.expected} but got "
            f"{[f['id'] for f in result.actual_findings]}"
        )


# ---------------------------------------------------------------------------
# 2. Negative controls: a clean tree must not produce a mutation finding
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("control", NEGATIVE_CONTROLS, ids=_CONTROL_IDS)
def test_negative_control_clean_tree_has_no_false_positive(
    control: Mutation, tmp_path: Path
) -> None:
    suite = _run_suite(tmp_path, [], [control])
    assert suite.false_positives == 0, (
        f"FALSE POSITIVE: clean tree produced {control.expected_finding_id}"
    )


# ---------------------------------------------------------------------------
# 3. Dynamism proof A: remove a detector → its mutation becomes MISSED
# ---------------------------------------------------------------------------
def test_removing_a_detector_turns_its_mutation_into_a_miss(tmp_path: Path) -> None:
    mutation = next(m for m in MUTATIONS if m.id == "F_false_capability")
    detector = "check_capability_implementation"

    # Baseline: the detector exists and catches the defect.
    before = _run(mutation, tmp_path / "before")
    assert before.detected is True

    # Remove the detector that catches this mutation.
    after = _run(mutation, tmp_path / "after", disabled=(detector,))
    assert after.detected is False, (
        "kill rate would still credit a detector that was removed"
    )


def test_disabled_detector_lowers_kill_rate(tmp_path: Path) -> None:
    mutation = next(m for m in MUTATIONS if m.id == "F_false_capability")
    with_detector = _run(mutation, tmp_path / "with")
    without_detector = _run(
        mutation, tmp_path / "without", disabled=("check_capability_implementation",)
    )
    assert with_detector.detected is True
    assert without_detector.detected is False
    # Recompute the suite rate with the mutation forced to a miss.
    full = _run_suite(tmp_path / "full", MUTATIONS, controls=[])
    forced = SuiteResult(mutations=[
        m if m.id != mutation.id else without_detector for m in full.mutations
    ])
    assert forced.kill_rate < full.kill_rate


# ---------------------------------------------------------------------------
# 4. Dynamism proof B: a new mutation changes the total automatically
# ---------------------------------------------------------------------------
def test_new_mutation_changes_total_without_code_edits(tmp_path: Path) -> None:
    baseline_total = len(MUTATIONS)
    extra = Mutation(
        id="U_extra_synthetic",
        name="extra_synthetic_help_reference",
        expected_finding_id="help.missing_topic",
        expected_severity="error",
        severity="medium",
        apply=lambda b: b.append(
            "frontend/src/views/AiView.vue",
            '\n<template><InfoHint topic="ghost_synthetic_topic" /></template>\n',
        ),
    )
    suite = _run_suite(tmp_path, [*MUTATIONS, extra], controls=[])
    assert suite.total == baseline_total + 1
    # The new mutation is classified by execution, not by declaration.
    new_result = next(m for m in suite.mutations if m.id == "U_extra_synthetic")
    assert new_result.detected is True


# ---------------------------------------------------------------------------
# 5. Isolation: the working tree is never mutated
# ---------------------------------------------------------------------------
def test_mutation_does_not_touch_the_working_tree(tmp_path: Path) -> None:
    target = (
        Path(__file__).resolve().parents[1]
        / "backend" / "app" / "services" / "reaction_service.py"
    )
    before = target.read_bytes()
    mutation = next(m for m in MUTATIONS if m.id == "F2_stray_string_mask")
    _run(mutation, tmp_path)
    assert target.read_bytes() == before, "a seeded defect leaked into production source"


def test_no_synthetic_defect_files_in_production_source() -> None:
    backend = Path(__file__).resolve().parents[1] / "backend" / "app"
    leaked = sorted(p.name for p in backend.rglob("zz_*"))
    assert not leaked, f"synthetic defect files leaked into production: {leaked}"


# ---------------------------------------------------------------------------
# 6. Sandbox restores module globals
# ---------------------------------------------------------------------------
def test_sandbox_restores_auditor_globals(tmp_path: Path) -> None:
    from backend.app.services import consistency_checks as cc

    root_before = cc.ROOT
    caps_before = cc.CAPABILITIES
    box = MutationSandbox.create(tmp_path)
    assert root_before != cc.ROOT
    box.restore()
    assert root_before == cc.ROOT
    assert cc.CAPABILITIES is caps_before
