"""Meta-audit core: silent-failure guard, runtime drift, generated kill rate.

Companion to ``tests/test_consistency_mutations.py``. It proves the guarantees
the Consistency Auditor must keep (D-099, D-102):

1. **A failing check never becomes a pass.** If a registered check raises, the
   runner emits ``audit.check_failed.<name>`` with severity ``error``.
2. **The runtime (DB-backed) checks detect real drift** — a dead setting and a
   channel-aware row without a channel reference.
3. **The kill rate is computed, not declared.** ``agent/META_AUDIT_RESULT.json``
   is generated by executing every mutation and classifying the result; it
   carries ``result_source: computed from runtime mutation executions`` and the
   arithmetic is asserted here and in CI.

No Telegram credentials, sessions, TDATA, network or production data are used.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path

import pytest
from httpx import AsyncClient

from backend.app import __version__
from backend.app.services.consistency import ConsistencyAuditor
from backend.app.services.consistency_types import (
    HEALTH_FAIL,
    SEVERITY_ERROR,
    build_report,
)
from tests.meta_audit.engine import (
    RESULT_SOURCE,
    report_path,
    run_suite,
    write_report,
)
from tests.meta_audit.mutations import KNOWN_GAP_IDS, MUTATIONS, NEGATIVE_CONTROLS

REPO_ROOT = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# 1. Silent-failure guard
# ---------------------------------------------------------------------------
def _run_with_broken_check(monkeypatch: pytest.MonkeyPatch, name: str) -> list:
    """Replace one static check with one that raises, then run the suite."""
    import backend.app.services.consistency_checks as cc

    def boom() -> list:
        raise RuntimeError("SYNTHETIC AUDIT FAILURE")

    boom.__name__ = name
    monkeypatch.setattr(cc, name, boom)
    return cc.run_static_checks()


def test_a_raising_static_check_is_reported_not_swallowed(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    findings = _run_with_broken_check(monkeypatch, "check_i18n_completeness")
    failed = [f for f in findings if f.id == "audit.check_failed.check_i18n_completeness"]
    assert failed, "a raising check disappeared instead of being reported"
    assert failed[0].severity == SEVERITY_ERROR


def test_a_raising_static_check_makes_the_report_fail(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    report = build_report(_run_with_broken_check(monkeypatch, "check_model_migration"))
    assert report.overall == HEALTH_FAIL
    assert report.counts[SEVERITY_ERROR] >= 1


def test_broken_source_check_reports_info_not_error(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # A source-comparison check must degrade to "unavailable" (info), never raise
    # into a false error, and never silently vanish (D-096).
    import backend.app.services.consistency_checks as cc

    monkeypatch.setattr(cc, "FRONTEND", tmp_path / "frontend-absent")
    findings = cc.run_static_checks()
    ids = {f.id for f in findings}
    assert "audit.source_unavailable.check_api_route_frontend_client" in ids
    assert "audit.source_unavailable.check_hardcoded_ui_strings" in ids
    assert not any(i.startswith("audit.check_failed.") for i in ids)
    unavailable = [f for f in findings if f.id.startswith("audit.source_unavailable.")]
    assert all(f.severity == "info" for f in unavailable)


async def test_a_raising_runtime_check_is_reported_not_swallowed(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    async def boom(self) -> list:
        raise RuntimeError("SYNTHETIC RUNTIME FAILURE")

    monkeypatch.setattr(ConsistencyAuditor, "_check_dead_settings", boom)
    from backend.app.db.session import get_session_factory

    async with get_session_factory()() as session:
        report = await ConsistencyAuditor(session).run()
    assert "audit.check_failed.boom" in {f.id for f in report.findings}
    assert report.overall == HEALTH_FAIL


# ---------------------------------------------------------------------------
# 2. Runtime (DB-backed) drift detection
# ---------------------------------------------------------------------------
async def test_runtime_detects_dead_setting(client: AsyncClient) -> None:
    # A persisted setting no module reads must surface as an orphan finding.
    from backend.app.db.repositories.settings import SettingRepository
    from backend.app.db.session import get_session_factory

    async with get_session_factory()() as session:
        await SettingRepository(session).upsert("zz_ghost_setting", "1", value_type="int")
        report = await ConsistencyAuditor(session).run()
    assert "settings.dead.zz_ghost_setting" in {f.id for f in report.findings}


async def test_runtime_detects_channel_aware_row_without_channel(
    client: AsyncClient,
) -> None:
    # A channel-aware table row with no channel_id must be flagged.
    from backend.app.db.models.content import ContentSource
    from backend.app.db.session import get_session_factory

    async with get_session_factory()() as session:
        session.add(ContentSource(title="ghost", reference="", channel_id=""))
        await session.commit()
        report = await ConsistencyAuditor(session).run()
    assert "channel-aware.content_source" in {f.id for f in report.findings}


# ---------------------------------------------------------------------------
# 3. The kill rate is generated by execution, not declared
# ---------------------------------------------------------------------------
def test_report_is_generated_from_runtime_execution(tmp_path: Path) -> None:
    out = tmp_path / "META_AUDIT_RESULT.json"

    async def _run():
        import tempfile

        with tempfile.TemporaryDirectory() as td:
            return await run_suite(Path(td), MUTATIONS, NEGATIVE_CONTROLS)

    suite = asyncio.run(_run())
    payload = write_report(suite, out)

    assert payload["result_source"] == RESULT_SOURCE
    # Every mutation carries a runtime-computed ``detected`` boolean.
    assert len(payload["mutations"]) == len(MUTATIONS)
    assert all(isinstance(m["detected"], bool) for m in payload["mutations"])
    # Arithmetic holds, computed from the executions.
    assert payload["detected"] + payload["missed"] == payload["total"]
    assert payload["kill_rate"] == round(payload["detected"] / payload["total"] * 100, 1)
    # Negative controls ran and produced no false positive.
    assert payload["false_positives"] == 0
    assert len(payload["negative_controls"]) == len(NEGATIVE_CONTROLS)
    # The committed report must match the same schema and provenance.
    committed = json.loads(report_path().read_text(encoding="utf-8"))
    assert committed["result_source"] == RESULT_SOURCE
    assert committed["detected"] + committed["missed"] == committed["total"]


def test_report_arithmetic_is_self_consistent(tmp_path: Path) -> None:
    async def _run():
        import tempfile

        with tempfile.TemporaryDirectory() as td:
            return await run_suite(Path(td), MUTATIONS, NEGATIVE_CONTROLS)

    suite = asyncio.run(_run())
    suite.verify()
    assert suite.detected + suite.missed == suite.total
    assert suite.kill_rate == round(suite.detected / suite.total * 100, 1)
    assert suite.critical_misses == sum(
        1 for m in suite.mutations if not m.detected and m.severity == "critical"
    )


# ---------------------------------------------------------------------------
# 4. Cross-file release hygiene
# ---------------------------------------------------------------------------
def test_repo_version_is_consistent() -> None:
    import tomllib

    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    package = json.loads((REPO_ROOT / "frontend" / "package.json").read_text(encoding="utf-8"))
    assert __version__ == pyproject["project"]["version"] == package["version"]


def test_readme_states_the_current_release() -> None:
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    assert f"`v{__version__}`" in readme


def test_result_report_matches_version() -> None:
    committed = json.loads(report_path().read_text(encoding="utf-8"))
    assert committed["version"] == __version__


# ---------------------------------------------------------------------------
# 5. Capability dependency actually blocks availability (not just a static warn)
# ---------------------------------------------------------------------------
def test_dependency_on_unimplemented_capability_blocks_availability(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import dataclasses

    from backend.app.services import capability_graph as cg

    donor = next(c for c in cg.CAPABILITIES if c.key == "donor_discovery")
    # ``media_conversion`` is registered but not implemented: a dependency on it
    # must block availability (``config_sync`` is implemented as of v1.6).
    patched = dataclasses.replace(donor, requires=("media_conversion",))
    monkeypatch.setattr(
        cg,
        "CAPABILITIES",
        tuple(patched if c.key == "donor_discovery" else c for c in cg.CAPABILITIES),
    )
    context = {req: True for cap in cg.CAPABILITIES for req in cap.requires}
    context["media_conversion"] = True
    state = cg.evaluate(patched, context)
    assert state.state != cg.STATE_AVAILABLE
    assert any("media_conversion" in m for m in state.missing)


# ---------------------------------------------------------------------------
# 6. Closed gaps M (write-only setting), N (unused DB field), O (service without
#    caller), P (frontend control without behaviour) and Q (channel-aware drift)
# ---------------------------------------------------------------------------
def _mutation(mutation_id: str):
    return next(m for m in MUTATIONS if m.id == mutation_id)


def test_write_only_setting_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """M: a setting written but never read must be flagged by the real auditor."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("M_write_only_setting"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "a write-only setting is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_channel_aware_module_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """Q: channel-aware code that bypasses the registry must be flagged."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("Q_channel_aware_module"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "a channel-aware module without a canonical link is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_unused_db_field_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """N: a column no module reads or writes must be flagged."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("N_unused_db_field"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "an unused DB column is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_service_without_caller_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """O: a public service class no module references must be flagged."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("O_service_without_caller"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "a backend service without a caller is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_control_without_behavior_mutation_is_detected_by_execution(tmp_path: Path) -> None:
    """P: a template handler with no defined function must be flagged."""
    from tests.meta_audit.engine import run_mutation

    result = asyncio.run(run_mutation(_mutation("P_control_without_behavior"), tmp_path))
    assert result.error is None
    assert result.detected is True, (
        "a frontend control without behaviour is no longer detected: "
        f"{[f['id'] for f in result.actual_findings]}"
    )


def test_all_original_gaps_are_closed() -> None:
    assert len(KNOWN_GAP_IDS) == 0
    for gap in (
        "M_write_only_setting",
        "N_unused_db_field",
        "O_service_without_caller",
        "P_control_without_behavior",
        "Q_channel_aware_module",
    ):
        assert gap not in KNOWN_GAP_IDS


@pytest.mark.parametrize(
    ("mutation_id", "detector"),
    [
        ("M_write_only_setting", "check_write_only_settings"),
        ("N_unused_db_field", "check_unused_model_columns"),
        ("O_service_without_caller", "check_orphan_service_classes"),
        ("P_control_without_behavior", "check_frontend_unwired_controls"),
        ("Q_channel_aware_module", "check_channel_registry_usage"),
    ],
)
def test_removing_a_gap_detector_turns_it_into_a_miss(
    mutation_id: str, detector: str, tmp_path: Path
) -> None:
    """Dynamism: removing each gap detector must flip its mutation back to MISS."""
    from tests.meta_audit.engine import run_mutation

    before = asyncio.run(run_mutation(_mutation(mutation_id), tmp_path / "before"))
    assert before.detected is True
    after = asyncio.run(
        run_mutation(
            _mutation(mutation_id), tmp_path / "after", disabled_checks=(detector,)
        )
    )
    assert after.detected is False


def test_committed_report_records_all_gaps_as_detected() -> None:
    committed = json.loads(report_path().read_text(encoding="utf-8"))
    by_id = {m["id"]: m for m in committed["mutations"]}
    for gap in (
        "M_write_only_setting",
        "N_unused_db_field",
        "O_service_without_caller",
        "P_control_without_behavior",
        "Q_channel_aware_module",
    ):
        assert by_id[gap]["detected"] is True, gap
    assert committed["high_misses"] == 0
    assert committed["missed"] == 0
    assert committed["kill_rate"] == 100.0
