"""v1.1 account hub proxies and donor discovery

Revision ID: 76d92fe3e70b
Revises: 7cb72d22d35b
Create Date: 2026-10-04 20:47:43.214471

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d92fe3e70b'
down_revision: str | None = '7cb72d22d35b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_candidates',
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.Column('avg_views', sa.Float(), nullable=False),
    sa.Column('activity', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('fit', sa.String(length=16), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('signals', sa.Text(), nullable=False),
    sa.Column('explanations', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('added', sa.Boolean(), nullable=False),
    sa.Column('added_source_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donor_candidates'))
    )
    with op.batch_alter_table('donor_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_candidates_query'), ['query'], unique=False)
        batch_op.create_index(batch_op.f('ix_donor_candidates_username'), ['username'], unique=False)

    op.create_table('proxy_profiles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('SOCKS5', 'HTTP', 'HTTPS', name='proxy_kind'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'OK', 'ERROR', 'TIMEOUT', name='proxy_status'), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxy_profiles'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('proxy_id', sa.String(length=32), nullable=False, server_default='')
        )
        batch_op.create_index(batch_op.f('ix_user_sessions_proxy_id'), ['proxy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_proxy_id'))
        batch_op.drop_column('proxy_id')

    op.drop_table('proxy_profiles')
    with op.batch_alter_table('donor_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_candidates_username'))
        batch_op.drop_index(batch_op.f('ix_donor_candidates_query'))

    op.drop_table('donor_candidates')
    # ### end Alembic commands ###
