"""baseline schema

Revision ID: 0191baf5265f
Revises: 
Create Date: 2026-10-03 21:24:21.552350

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0191baf5265f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_metrics',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('rules_count', sa.Integer(), nullable=False),
    sa.Column('ai_count', sa.Integer(), nullable=False),
    sa.Column('fallback_count', sa.Integer(), nullable=False),
    sa.Column('manual_count', sa.Integer(), nullable=False),
    sa.Column('ai_error_count', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('last_latency_ms', sa.Integer(), nullable=False),
    sa.Column('model_load_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_metrics')),
    sa.UniqueConstraint('name', name=op.f('uq_ai_metrics_name'))
    )
    op.create_table('ai_records',
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('tone', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_records'))
    )
    with op.batch_alter_table('ai_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_records_source'), ['source'], unique=False)

    op.create_table('audience_users',
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=160), nullable=False),
    sa.Column('last_name', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('phone_masked', sa.String(length=32), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', 'BLOCKED', 'UNKNOWN', name='audience_member_status'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_reason', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_status', sa.String(length=32), nullable=False),
    sa.Column('invite_attempts', sa.Integer(), nullable=False),
    sa.Column('last_invite_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_invite_error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audience_users')),
    sa.UniqueConstraint('telegram_user_id', name='uq_audience_users_telegram_user_id')
    )
    with op.batch_alter_table('audience_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_users_is_bot'), ['is_bot'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_users_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_users_telegram_user_id'), ['telegram_user_id'], unique=False)

    op.create_table('bots',
    sa.Column('kind', sa.Enum('MANAGER', 'MANAGED', 'ORDINARY', name='bot_kind'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('token_encrypted', sa.Text(), nullable=False),
    sa.Column('provider_name', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_username', sa.String(length=64), nullable=False),
    sa.Column('can_manage_bots', sa.Boolean(), nullable=True),
    sa.Column('health', sa.Enum('UNKNOWN', 'OK', 'WARNING', 'ERROR', name='bot_health'), nullable=False),
    sa.Column('health_message', sa.Text(), nullable=False),
    sa.Column('health_hint', sa.Text(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bots'))
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bots_kind'), ['kind'], unique=False)

    op.create_table('events',
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='event_level'), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('how_to_fix', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_level_created', ['level', 'created_at'], unique=False)

    op.create_table('invite_jobs',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('target_title', sa.String(length=255), nullable=False),
    sa.Column('account_ids', sa.Text(), nullable=False),
    sa.Column('source_ids', sa.Text(), nullable=False),
    sa.Column('filters', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'RUNNING', 'PAUSED', 'COMPLETED', 'STOPPED', 'FAILED', name='invite_job_status'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_summary', sa.Text(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('per_account_delay_min', sa.Float(), nullable=False),
    sa.Column('per_account_delay_max', sa.Float(), nullable=False),
    sa.Column('max_per_account', sa.Integer(), nullable=False),
    sa.Column('max_total', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('invited_count', sa.Integer(), nullable=False),
    sa.Column('already_count', sa.Integer(), nullable=False),
    sa.Column('privacy_count', sa.Integer(), nullable=False),
    sa.Column('flood_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('waiting_account_id', sa.String(length=32), nullable=False),
    sa.Column('wait_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_job_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_jobs'))
    )
    with op.batch_alter_table('invite_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_invite_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('invite_tasks',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'INVITED', 'ALREADY_MEMBER', 'SKIPPED', 'PRIVACY', 'FLOOD_WAIT', 'ADMIN_REQUIRED', 'FAILED', name='invite_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wait_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_tasks')),
    sa.UniqueConstraint('job_id', 'user_id', name='uq_invite_task_job_user')
    )
    with op.batch_alter_table('invite_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_tasks_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_tasks_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_invite_tasks_job_status', ['job_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('job_queue',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'RUNNING', 'DONE', 'FAILED', 'CANCELLED', 'PAUSED', name='job_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_queue'))
    )
    with op.batch_alter_table('job_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_queue_group_key'), ['group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_queue_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_queue_status'), ['status'], unique=False)
        batch_op.create_index('ix_job_queue_status_scheduled', ['status', 'scheduled_at'], unique=False)

    op.create_table('permission_checks',
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('account_label', sa.String(length=160), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('target_title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel_found', sa.Boolean(), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('can_read_info', sa.Boolean(), nullable=False),
    sa.Column('can_read_participants', sa.Boolean(), nullable=False),
    sa.Column('can_invite', sa.Boolean(), nullable=False),
    sa.Column('session_ok', sa.Boolean(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('participants_count', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('how_to_fix', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_checks'))
    )
    with op.batch_alter_table('permission_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_checks_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_checks_status'), ['status'], unique=False)

    op.create_table('posts',
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_username', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('category_title', sa.String(length=64), nullable=False),
    sa.Column('classification_source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('matched_terms', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CLASSIFIED', 'PLANNED', 'PROCESSING', 'DONE', 'SKIPPED', 'FAILED', name='post_status'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_telegram_message_id'), ['telegram_message_id'], unique=False)

    op.create_table('reaction_jobs',
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('bot_id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('reaction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'SCHEDULED', 'RUNNING', 'DONE', 'FAILED', 'SKIPPED', 'CANCELLED', name='reaction_job_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('queue_job_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction_jobs'))
    )
    with op.batch_alter_table('reaction_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reaction_jobs_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reaction_jobs_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reaction_jobs_queue_job_id'), ['queue_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reaction_jobs_status'), ['status'], unique=False)

    op.create_table('reaction_profiles',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('allowed_emoji', sa.Text(), nullable=False),
    sa.Column('emoji_weights', sa.Text(), nullable=False),
    sa.Column('participation_probability', sa.Float(), nullable=False),
    sa.Column('skip_probability', sa.Float(), nullable=False),
    sa.Column('delay_min', sa.Float(), nullable=False),
    sa.Column('delay_max', sa.Float(), nullable=False),
    sa.Column('delay_preset', sa.Enum('EARLY', 'NORMAL', 'SPREAD', name='delay_preset'), nullable=False),
    sa.Column('max_bots_per_post', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction_profiles'))
    )
    with op.batch_alter_table('reaction_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reaction_profiles_enabled'), ['enabled'], unique=False)

    op.create_table('reaction_rules',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('phrases', sa.Text(), nullable=False),
    sa.Column('regexes', sa.Text(), nullable=False),
    sa.Column('exclusions', sa.Text(), nullable=False),
    sa.Column('allowed_reactions', sa.Text(), nullable=False),
    sa.Column('preferred_reactions', sa.Text(), nullable=False),
    sa.Column('forbidden_reactions', sa.Text(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction_rules'))
    )
    with op.batch_alter_table('reaction_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reaction_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_reaction_rules_enabled'), ['enabled'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('user_sessions',
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('phone_masked', sa.String(length=32), nullable=False),
    sa.Column('api_id', sa.String(length=32), nullable=False),
    sa.Column('phone_encrypted', sa.Text(), nullable=False),
    sa.Column('api_hash_encrypted', sa.Text(), nullable=False),
    sa.Column('session_ref', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'AUTH_REQUIRED', 'DISCONNECTED', 'FLOOD_WAIT', 'ERROR', 'DISABLED', name='session_status'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auth_step', sa.String(length=16), nullable=False),
    sa.Column('phone_code_hash', sa.String(length=128), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=False),
    sa.Column('status_hint', sa.Text(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_telegram_user_id'), ['telegram_user_id'], unique=False)

    op.create_table('audience_sources',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('CHANNEL', 'GROUP', 'ENTITY', 'UNKNOWN', name='audience_source_type'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('scan_status', sa.Enum('IDLE', 'SCANNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='audience_scan_status'), nullable=False),
    sa.Column('completeness', sa.Enum('UNKNOWN', 'COMPLETE', 'PARTIAL', 'FAILED', 'NO_ACCESS', name='audience_completeness'), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('reported_total', sa.Integer(), nullable=True),
    sa.Column('scanned_offset', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_sessions.id'], name=op.f('fk_audience_sources_account_id_user_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audience_sources')),
    sa.UniqueConstraint('telegram_id', name='uq_audience_sources_telegram_id')
    )
    with op.batch_alter_table('audience_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_sources_scan_status'), ['scan_status'], unique=False)
        batch_op.create_index('ix_audience_sources_status', ['scan_status', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_sources_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_sources_username'), ['username'], unique=False)

    op.create_table('audience_source_users',
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovery_method', sa.String(length=32), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['audience_sources.id'], name=op.f('fk_audience_source_users_source_id_audience_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['audience_users.id'], name=op.f('fk_audience_source_users_user_id_audience_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audience_source_users')),
    sa.UniqueConstraint('source_id', 'user_id', name='uq_source_user')
    )
    with op.batch_alter_table('audience_source_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_source_users_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_source_users_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_source_users_source_user', ['source_id', 'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audience_source_users', schema=None) as batch_op:
        batch_op.drop_index('ix_source_users_source_user')
        batch_op.drop_index(batch_op.f('ix_audience_source_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_audience_source_users_source_id'))

    op.drop_table('audience_source_users')
    with op.batch_alter_table('audience_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_sources_username'))
        batch_op.drop_index(batch_op.f('ix_audience_sources_telegram_id'))
        batch_op.drop_index('ix_audience_sources_status')
        batch_op.drop_index(batch_op.f('ix_audience_sources_scan_status'))

    op.drop_table('audience_sources')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_telegram_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('reaction_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reaction_rules_enabled'))
        batch_op.drop_index(batch_op.f('ix_reaction_rules_category'))

    op.drop_table('reaction_rules')
    with op.batch_alter_table('reaction_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reaction_profiles_enabled'))

    op.drop_table('reaction_profiles')
    with op.batch_alter_table('reaction_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reaction_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_reaction_jobs_queue_job_id'))
        batch_op.drop_index(batch_op.f('ix_reaction_jobs_post_id'))
        batch_op.drop_index(batch_op.f('ix_reaction_jobs_bot_id'))

    op.drop_table('reaction_jobs')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_telegram_message_id'))
        batch_op.drop_index(batch_op.f('ix_posts_status'))
        batch_op.drop_index(batch_op.f('ix_posts_channel_id'))
        batch_op.drop_index(batch_op.f('ix_posts_category'))

    op.drop_table('posts')
    with op.batch_alter_table('permission_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_checks_status'))
        batch_op.drop_index(batch_op.f('ix_permission_checks_account_id'))

    op.drop_table('permission_checks')
    with op.batch_alter_table('job_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_job_queue_status_scheduled')
        batch_op.drop_index(batch_op.f('ix_job_queue_status'))
        batch_op.drop_index(batch_op.f('ix_job_queue_kind'))
        batch_op.drop_index(batch_op.f('ix_job_queue_group_key'))

    op.drop_table('job_queue')
    with op.batch_alter_table('invite_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_invite_tasks_status'))
        batch_op.drop_index('ix_invite_tasks_job_status')
        batch_op.drop_index(batch_op.f('ix_invite_tasks_job_id'))
        batch_op.drop_index(batch_op.f('ix_invite_tasks_account_id'))

    op.drop_table('invite_tasks')
    with op.batch_alter_table('invite_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_invite_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_invite_jobs_status'))

    op.drop_table('invite_jobs')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_level_created')

    op.drop_table('events')
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bots_kind'))

    op.drop_table('bots')
    with op.batch_alter_table('audience_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_users_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_audience_users_status'))
        batch_op.drop_index(batch_op.f('ix_audience_users_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_audience_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_audience_users_is_bot'))

    op.drop_table('audience_users')
    with op.batch_alter_table('ai_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_records_source'))

    op.drop_table('ai_records')
    op.drop_table('ai_metrics')
    # ### end Alembic commands ###
