"""channel registry

Revision ID: 561f0631d045
Revises: 0191baf5265f
Create Date: 2026-10-03 21:24:32.680188

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561f0631d045'
down_revision: str | None = '0191baf5265f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('CHANNEL', 'GROUP', 'SUPERGROUP', 'UNKNOWN', name='channel_kind'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'VERIFIED', 'WARNING', 'ERROR', 'DISABLED', name='channel_status'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('modules', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verification_message', sa.Text(), nullable=False),
    sa.Column('verification_hint', sa.Text(), nullable=False),
    sa.Column('participants_count', sa.BigInteger(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels'))
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_channels_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_channels_telegram_id'), ['telegram_id'], unique=False)

    with op.batch_alter_table('invite_jobs', schema=None) as batch_op:
        # server_default lets the column be added to a table that already has
        # rows (SQLite requires a default for a NOT NULL column).
        batch_op.add_column(
            sa.Column('channel_id', sa.String(length=64), nullable=False, server_default='')
        )
        batch_op.create_index(batch_op.f('ix_invite_jobs_channel_id'), ['channel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_jobs_channel_id'))
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_channels_status'))
        batch_op.drop_index(batch_op.f('ix_channels_reference'))

    op.drop_table('channels')
    # ### end Alembic commands ###
