"""product slice: bindings, capabilities, campaigns, donors, destinations, onboarding, update

Revision ID: 7cb72d22d35b
Revises: 6816b29afc76
Create Date: 2026-10-04 19:06:06.484624

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb72d22d35b'
down_revision: str | None = '6816b29afc76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_destinations',
    sa.Column('kind', sa.Enum('LOCAL', 'GOOGLE_DRIVE', 'YANDEX_DISK', 'TELEGRAM', name='destination_kind'), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('NOT_CONFIGURED', 'CONNECTED', 'WARNING', 'ERROR', 'DISABLED', name='destination_status'), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('account_label', sa.String(length=160), nullable=False),
    sa.Column('last_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('available_space', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_destinations'))
    )
    with op.batch_alter_table('backup_destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_destinations_kind'), ['kind'], unique=False)

    op.create_table('bot_channel_bindings',
    sa.Column('bot_id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('channel_label', sa.String(length=255), nullable=False),
    sa.Column('function', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('NOT_CONNECTED', 'CONNECTED', 'NEEDS_PERMISSION', 'READY', 'ERROR', name='binding_status'), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATOR', 'MEMBER', 'LEFT', 'UNKNOWN', name='binding_role'), nullable=False),
    sa.Column('can_post_messages', sa.Boolean(), nullable=False),
    sa.Column('can_edit_messages', sa.Boolean(), nullable=False),
    sa.Column('can_delete_messages', sa.Boolean(), nullable=False),
    sa.Column('can_manage_chat', sa.Boolean(), nullable=False),
    sa.Column('can_invite_users', sa.Boolean(), nullable=False),
    sa.Column('can_set_reactions', sa.Boolean(), nullable=False),
    sa.Column('invite_link', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_channel_bindings')),
    sa.UniqueConstraint('bot_id', 'channel_id', 'function', name='uq_binding_bot_channel_fn')
    )
    with op.batch_alter_table('bot_channel_bindings', schema=None) as batch_op:
        batch_op.create_index('ix_bindings_channel_status', ['channel_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_channel_bindings_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_channel_bindings_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_channel_bindings_status'), ['status'], unique=False)

    op.create_table('channel_capabilities',
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('available_reactions', sa.Text(), nullable=False),
    sa.Column('bot_reactions', sa.Text(), nullable=False),
    sa.Column('reactions_limit', sa.Integer(), nullable=False),
    sa.Column('paid_reactions_available', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_capabilities'))
    )
    with op.batch_alter_table('channel_capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_capabilities_channel_id'), ['channel_id'], unique=True)

    op.create_table('donor_metrics',
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('posts_per_week', sa.Float(), nullable=False),
    sa.Column('avg_views', sa.Float(), nullable=False),
    sa.Column('view_subscriber_ratio', sa.Float(), nullable=False),
    sa.Column('reaction_view_ratio', sa.Float(), nullable=False),
    sa.Column('avg_comments', sa.Float(), nullable=False),
    sa.Column('days_since_last_post', sa.Integer(), nullable=False),
    sa.Column('growth_percent', sa.Float(), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('bot_probability', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('participant_data', sa.Boolean(), nullable=False),
    sa.Column('bot_share_estimate', sa.Float(), nullable=True),
    sa.Column('signals', sa.Text(), nullable=False),
    sa.Column('explanations', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_completeness', sa.String(length=16), nullable=False),
    sa.Column('last_analyzed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donor_metrics'))
    )
    with op.batch_alter_table('donor_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_metrics_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donor_metrics_source_id'), ['source_id'], unique=True)

    op.create_table('invite_campaigns',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('target_title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'DISABLED', name='campaign_status'), nullable=False),
    sa.Column('risk_mode', sa.String(length=16), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('links_count', sa.Integer(), nullable=False),
    sa.Column('joins_count', sa.Integer(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_campaigns'))
    )
    with op.batch_alter_table('invite_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_campaigns_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_campaigns_status'), ['status'], unique=False)

    op.create_table('invite_links',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'REVOKED', 'EXPIRED', 'ERROR', name='link_status'), nullable=False),
    sa.Column('join_request', sa.Boolean(), nullable=False),
    sa.Column('member_limit', sa.Integer(), nullable=False),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joins_count', sa.Integer(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_links'))
    )
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_links_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_links_status'), ['status'], unique=False)

    op.create_table('join_requests',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('link_id', sa.String(length=32), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', 'UNKNOWN', name='join_request_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_join_requests'))
    )
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_join_requests_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_join_requests_link_id'), ['link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_join_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_join_requests_telegram_user_id'), ['telegram_user_id'], unique=False)

    op.create_table('promotion_progress',
    sa.Column('preset', sa.String(length=24), nullable=False),
    sa.Column('current_step', sa.String(length=32), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('completed_steps', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_progress'))
    )
    op.create_table('update_state',
    sa.Column('auto_update_enabled', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('current_version', sa.String(length=32), nullable=False),
    sa.Column('latest_version', sa.String(length=32), nullable=False),
    sa.Column('release_url', sa.String(length=255), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=False),
    sa.Column('staged_file', sa.String(length=255), nullable=False),
    sa.Column('staged_sha256', sa.String(length=64), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_update_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_state')
    op.drop_table('promotion_progress')
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_join_requests_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_join_requests_status'))
        batch_op.drop_index(batch_op.f('ix_join_requests_link_id'))
        batch_op.drop_index(batch_op.f('ix_join_requests_campaign_id'))

    op.drop_table('join_requests')
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_links_status'))
        batch_op.drop_index(batch_op.f('ix_invite_links_campaign_id'))

    op.drop_table('invite_links')
    with op.batch_alter_table('invite_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_invite_campaigns_channel_id'))

    op.drop_table('invite_campaigns')
    with op.batch_alter_table('donor_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_metrics_source_id'))
        batch_op.drop_index(batch_op.f('ix_donor_metrics_channel_id'))

    op.drop_table('donor_metrics')
    with op.batch_alter_table('channel_capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_capabilities_channel_id'))

    op.drop_table('channel_capabilities')
    with op.batch_alter_table('bot_channel_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_channel_bindings_status'))
        batch_op.drop_index(batch_op.f('ix_bot_channel_bindings_channel_id'))
        batch_op.drop_index(batch_op.f('ix_bot_channel_bindings_bot_id'))
        batch_op.drop_index('ix_bindings_channel_status')

    op.drop_table('bot_channel_bindings')
    with op.batch_alter_table('backup_destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_destinations_kind'))

    op.drop_table('backup_destinations')
    # ### end Alembic commands ###
